<?php
/*
Template Name: Contact Us
*/

get_header();
?>

<main class="contact-page bg-tt-light-bg">
    
    <!-- Hero Section -->
    <section class="contact-hero py-16 lg:py-20 px-4 sm:px-8 lg:px-16">
        <div class="max-w-7xl mx-auto grid lg:grid-cols-2 gap-8 lg:gap-12 items-start">
            
            <!-- Left: Heading -->
            <div>
                <h1 class="heading-font text-5xl sm:text-6xl lg:text-7xl font-medium text-tt-dark-navy leading-tight">
                    Contact Us
                </h1>
            </div>
            
            <!-- Right: Description -->
            <div class="lg:pt-8">
                <p class="text-tt-dark-navy/80 text-base sm:text-lg leading-relaxed">
                    We'd love to hear from you! Whether you're planning your big day or have questions about our services, reach out to start capturing your unforgettable moments with Golden Memories.
                </p>
            </div>
            
        </div>
    </section>

    <!-- Contact Form Section -->
    <section class="contact-form-section pb-16 lg:pb-24 px-4 sm:px-8 lg:px-16">
        <div class="max-w-7xl mx-auto">
            <div class="grid lg:grid-cols-2 gap-8 lg:gap-12 items-center">
                
                <!-- Left: Image -->
                <div class="order-2 lg:order-1">
                    <div class="contact-image-frame">
                        <img src="https://images-pw.pixieset.com/elementfield/83642509/Amisha__Deepan_Wedding-931-596a10c7.jpg" 
                             alt="Wedding couple" 
                             class="w-full h-full object-cover">
                    </div>
                </div>
                
                <!-- Right: Form -->
                <div class="order-1 lg:order-2">
                    
                <form id="ajax-contact-form" class="contact-form">

                <!-- a unique security token generated by WordPress.
                Why it’s needed: It prevents CSRF (Cross-Site Request Forgery). -->
                    <input type="hidden" name="action" value="submit_contact_form">
                    <input type="hidden" name="security" value="<?php echo wp_create_nonce('ajax_contact_nonce'); ?>">

                    <div class="form-group">
                        <label>Name *</label>
                        <input type="text" name="name" class="form-input" required>
                    </div>

                    <div class="form-group">
                        <label>Email *</label>
                        <input type="email" name="email" class="form-input" required>
                    </div>

                    <div class="form-group">
                        <label>Address *</label>
                        <input type="text" name="address" class="form-input" required>
                    </div>                    

                    <div class="form-group">
                        <label>Message *</label>
                        <textarea name="message" class="form-input" required></textarea>
                    </div><br><br>

                    <button type="submit" class="btn-send-message">Send Message</button>

                    <p id="form-response" class="mt-4"></p>
                </form>

                </div>
                
            </div>
        </div>
    </section>

    <!-- Google Map Section -->
    <?php if( get_field('google_map', 'option') ): 
        $location = get_field('google_map', 'option'); ?>
        <section class="map-section pb-16 lg:pb-24 px-4 sm:px-8 lg:px-16">
            <div class="max-w-7xl mx-auto">
                <div class="map-container rounded-lg overflow-hidden shadow-xl">
                    <iframe
                        width="100%"
                        height="450"
                        style="border:0"
                        loading="lazy"
                        allowfullscreen
                        src="https://www.google.com/maps?q=<?php echo esc_attr($location['lat']); ?>,<?php echo esc_attr($location['lng']); ?>&hl=en&z=14&output=embed">
                    </iframe>
                </div>
            </div>
        </section>
    <?php endif; ?>

</main>

<?php get_footer(); ?>
